# Generated by Django 5.0.6 on 2024-10-13 15:21

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='docr_report_image',
            new_name='doctor_report_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='matno',
            new_name='matric_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nextofkin',
            new_name='next_of_kin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nextofkin_mobile',
            new_name='next_of_kin_mobile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123', length=7, max_length=25, prefix=''),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
