# Generated by Django 5.0.6 on 2024-12-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_rename_docr_report_image_profile_doctor_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_of_kin_mobile',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
