# Generated by Django 5.0.6 on 2024-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_profile_other_health_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
