# Generated by Django 5.0.6 on 2025-01-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_medicalcondition_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalCondition',
            new_name='Condition',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medical_conditions',
        ),
        migrations.AddField(
            model_name='profile',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='Select your condition(s) from the list', related_name='profiles', to='userauth.condition'),
        ),
    ]
