# Generated by Django 5.0.6 on 2025-01-07 22:05

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_rename_medicalcondition_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor_report_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='proof_image',
            field=models.FileField(blank=True, default='default.jpg', help_text='submit doctors reports, executive IDs or any other form of proof', null=True, upload_to=userauth.models.user_directory_path),
        ),
    ]
