# Generated by Django 5.0.6 on 2025-01-10 00:27

import django.db.models.deletion
import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_hostel_block_room_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block_preference',
            field=models.ForeignKey(blank=True, help_text='Select your preferred block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='userauth.hostel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proof_image',
            field=models.FileField(blank=True, default='default.jpg', help_text="Submit doctor's reports, executive IDs, or any other form of proof", null=True, upload_to=userauth.models.user_directory_path),
        ),
    ]
