# Generated by Django 5.0.6 on 2025-01-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_alter_block_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_preference',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Select your preferred block', max_length=100, null=True),
        ),
    ]
