# Generated by Django 5.0.6 on 2025-01-10 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_alter_block_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block_preference',
            field=models.ForeignKey(blank=True, help_text='Select your preferred block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='userauth.block'),
        ),
    ]
