# Generated by Django 5.0.6 on 2025-01-10 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_alter_profile_block_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel_preference',
            field=models.ForeignKey(blank=True, help_text='Select your preferred hostel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_profiles', to='userauth.hostel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_preference',
            field=models.ForeignKey(blank=True, help_text='Select your preferred block under the selected hostel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_profiles', to='userauth.block'),
        ),
    ]
