# Generated by Django 5.0.6 on 2025-01-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_profile_hostel_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hostel_preference',
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_preference',
            field=models.ForeignKey(blank=True, help_text='Select your preferred block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='userauth.hostel'),
        ),
    ]
