# Generated by Django 5.0.6 on 2025-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0018_remove_profile_hostel_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='occupied_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='assigned_levels',
            field=models.JSONField(blank=True, default=list, help_text='Levels to which this hostel is assigned'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], max_length=100),
        ),
    ]
