# Generated by Django 5.0.6 on 2025-01-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_block_occupied_rooms_hostel_assigned_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='occupied_rooms',
        ),
    ]
