# Generated by Django 5.0.6 on 2025-01-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0020_remove_block_occupied_rooms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('hostel', 'name')},
        ),
    ]
