# Generated by Django 5.0.6 on 2025-01-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0021_alter_block_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'name')},
        ),
    ]
