# Generated by Django 5.0.6 on 2025-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0022_alter_room_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='allocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='assigned_levels',
        ),
        migrations.AddField(
            model_name='hostel',
            name='assigned_levels',
            field=models.ManyToManyField(blank=True, help_text='Levels to which this hostel is assigned', related_name='hostels', to='userauth.level'),
        ),
    ]
