# Generated by Django 5.0.6 on 2025-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0023_level_alter_allocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='block_preference',
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=1),
        ),
    ]
