# Generated by Django 5.0.6 on 2025-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0025_remove_profile_conditions_profile_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='conditions',
        ),
        migrations.AddField(
            model_name='profile',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='Select your condition(s) from the list', related_name='profiles', to='userauth.condition'),
        ),
    ]
