# Generated by Django 5.0.6 on 2025-01-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0027_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='request',
            name='priority',
        ),
    ]
