# Generated by Django 5.0.6 on 2025-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0028_alter_request_options_remove_request_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
