# Generated by Django 5.0.6 on 2025-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0029_universityimage_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to student)', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text="Priority level based on student's condition"),
        ),
    ]
