# Generated by Django 5.0.6 on 2025-02-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0030_alter_request_options_request_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='read',
            field=models.BooleanField(default=False, help_text='Mark if student has seen this rejection'),
        ),
    ]
