# Generated by Django 5.0.6 on 2025-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0031_request_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
